---
- name: Include vscode playbook
  ansible.builtin.import_playbook: vscode.yml
  when: install_vscode | bool

- name: Include zed playbook
  ansible.builtin.import_playbook: zed.yml
  when: install_zed | bool

- name: Include zsh playbook
  ansible.builtin.import_playbook: zsh.yml
  when: install_zsh | bool

- name: Include ferdium playbook
  ansible.builtin.import_playbook: ferdium.yml
  when: install_ferdium | bool

- name: Include docker playbook
  ansible.builtin.import_playbook: docker.yml
  when: install_docker | bool

- name: Include packages playbook
  ansible.builtin.import_playbook: packages.yml
  when: packages is defined

- name: Include spotify playbook
  ansible.builtin.import_playbook: spotify.yml
  when: install_spotify | bool

- name: Include chrome playbook
  ansible.builtin.import_playbook: chrome.yml
  when: install_chrome | bool

- name: Include restic playbook
  ansible.builtin.import_playbook: restic.yml
  when: install_restic | bool

- name: Include aws-cli playbook
  ansible.builtin.import_playbook: aws_cli.yml
  when: install_aws_cli | bool
